plugin-testng: Plugin initial commit
harness-community/drone-testng pull request #1
Opened 2024-12-09 04:36 UTC by vanisrikanithi

Plugin-TestNG: This PR includes the Implementation of TestNG plugin to support processing the TestNG XML reports.

For Harness CI Pipeline test result please click on the link [here](https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/module/ci/orgs/default/projects/jenkinstoharness/pipelines/Vani_TestNG/deployments/c2C2V9LmSpG9ysjN4xOB8w/pipeline?storeType=INLINE)

For Harness Test Release Pipeline of Testng plugin click [here](https://app.harness.io/ng/account/gCoPSwHxS7ipOgx2iA9tOQ/module/ci/orgs/default/projects/jenkinstoharness/pipelines/VaniTestNGdronereleasepipeline/deployments/qLRb8gTgTOy56PP3xy3qBQ/pipeline?storeType=INLINE&stage=JMdv8BloTPaTtEaHezQP1A&step=7dWREgVQRSeBlFXrQ08pDg&childStage=&stageExecId=)

@Ompragash Please review the PR for TestNG plugin and add your comments if there are any.

2024-12-09 17:32 UTC, Ompragash requested changes

2024-12-09 17:32 UTC, Ompragash commented on plugin/plugin.go
> +		logrus.Warn("No TestNG XML report files found, continuing execution as PluginFailIfNoResults is false")
lets remove PluginFailIfNoResults and just throw error when the report file isn't available

2024-12-09 17:32 UTC, Ompragash commented on plugin/plugin.go
> +	UnstableSkips             int    `envconfig:"PLUGIN_UNSTABLE_SKIPS"`
let's remove inputs related to unstable as Harness doesn't support the pipeline status as unstable

2024-12-09 17:32 UTC, Ompragash commented on plugin/plugin_test.go
remove tests covering unstable and also add tests for below:
- incorrect XML structure
- mixed valid and invalid files
- edge case: validate plugin behaviour with very high values or empty results

2024-12-09 17:32 UTC, Ompragash commented on README.md
> +## TestNG: This plugin converts TestNG XML reports (generated using org.testng.reporters.XMLReporter) to JUnit-compatible XML reports, enforcing thresholds and configuration validations to manage bui
please remove this and the references of Junit if any

2024-12-09 20:18 UTC, Ompragash requested changes

2024-12-09 20:18 UTC, Ompragash commented on plugin/plugin.go
> +	if args.ThresholdMode != 1 && args.ThresholdMode != 2 {
instead of 1 and 2, users can directly input `absolute` or `percentage` which are self-explanatory and also set the below constants with a default thresholdmode and update the switch case in `validateThresholds` accordingly 
```go
const (
    ThresholdModeAbsolute   = "absolute"
    ThresholdModePercentage = "percentage"
    DefaultThresholdMode    = ThresholdModeAbsolute // Default value
)
```

with the above default, when no PLUGIN_THRESHOLD_MODE set by the user, mode `absolute` will be used and logs the below
```
PLUGIN_THRESHOLD_MODE not specified. Defaulting to 'absolute'
```

update the same in the readme as well

2024-12-09 20:18 UTC, Ompragash commented on plugin/plugin.go
> +func locateFiles(pattern string) ([]string, error) {
add checks for file read permissions to prevent runtime errors and log the number of files found for clarity

2024-12-09 20:18 UTC, Ompragash commented on plugin/plugin.go
> +func processFile(filename string) (Results, error) {
add logic to handle permission issues and log errors. make sure the logs are clear between `file not found` & `parsing error` errors

2024-12-09 20:18 UTC, Ompragash commented on plugin/plugin.go
> +		return Results{}, errors.New("failed to parse TestNG XML: " + err.Error())
- validate essential fields like Suites and Classes are present and non-empty, also warn about structural issues in the XML content, like missing test classes or empty suites like "File testng-report.xml contains no test suites in the XML structure"

- also in case of multiple reports parsing, if parsing one report fails, add logic to skip the file and continue processing other reports

2024-12-09 20:18 UTC, Ompragash commented on plugin/plugin.go
> +		return nil // No tests to validate
```suggestion
	if totalTests == 0 {
	        logrus.Warn("No tests executed; skipping percentage-based threshold validation.")
		return nil
```

also add a test case to verify behavior when no tests are executed

2024-12-09 20:18 UTC, Ompragash commented on plugin/plugin.go
> +func validateAbsoluteThresholds(results Results, args Args) error {
move the repetitive checks into helper functions and make use of them in both validateAbsoluteThresholds and validatePercentageThresholds

2024-12-09 20:18 UTC, Ompragash commented on plugin/plugin.go
> +func logTestNGReportDetails(report TestNGReport) Results {
add check to handle invalid durations by adding a warning log for invalid or missing DurationMS values and also log suite-level summaries 

again create helper functions to reduce duplication in aggregation logic

once the above completed, add uts for aggregation logic

2024-12-09 20:18 UTC, Ompragash commented on plugin/plugin.go
> +	data, err := os.ReadFile(filename)
instead of loading the entire file into memory using os.ReadFile use xml.Decoder for streaming to avoid memory spike and test the behaviour

2024-12-13 17:45 UTC, Ompragash requested changes
after addressing the changes, build and push the images for both Linux and Windows and share the test execution link

2024-12-13 17:45 UTC, Ompragash commented on plugin/plugin.go
> +	}
```suggestion
        var (
                resultsChan    = make(chan Results, len(files))
                errorsChan     = make(chan error, len(files))
        )
        
        for _, file := range files {
	        go func(f string) {
		        res, err := processFile(f)
		        if err != nil {
			        errorsChan <- fmt.Errorf("failed to process file %s: %w", f, err)
			        return
		        }
		        resultsChan <- res
	        }(file)
        }
        
	var aggregatedResults Results
	var skippedFiles []string
	
	for i := 0; i < len(files); i++ {
	        select {
	        case res := <-resultsChan:
		        aggregatedResults.Total += res.Total
		        aggregatedResults.Failures += res.Failures
		        aggregatedResults.Skipped += res.Skipped
		        aggregatedResults.DurationMS += res.DurationMS
	        case err := <-errorsChan:
		        logrus.Warn(err)
			if e, ok := err.(*os.PathError); ok {
			        skippedFiles = append(skippedFiles, e.Path)
			}
	        }
	}
```

let's implement parallel processing in case of large number of files

2024-12-13 17:45 UTC, Ompragash commented on plugin/plugin.go
> +	}
also add tests with a mix of valid and invalid files in a parallel processing scenario

2024-12-13 19:55 UTC, vanisrikanithi commented
@Ompragash  added parallel process code and tested successfully, could you please check it and confirm..

2024-12-18 03:38 UTC, Ompragash commented on plugin/plugin.go
> +		logrus.Infof("\nTest case Skips: %s", formatTestNames(skippedTests))
```suggestion
		logrus.Infof("\nFailed Test cases: %s", formatTestNames(failedTests))
	}
	if len(skippedTests) > 0 {
		logrus.Infof("\nSkipped Test cases: %s", formatTestNames(skippedTests))
```
<img width="818" alt="Screenshot 2024-12-17 at 8 56 54 PM" src="https://github.com/user-attachments/assets/1df8ee4c-b712-4e67-9c72-176929308e27" />
add `======` before `Failed Test cases` for clarity

2024-12-18 18:11 UTC, Ompragash approved these changes

2024-12-18 18:11 UTC, merged